### ISSUE TITLE
[Feature] Docker image

### ISSUE THREAD

**Issue by ToshY** [drawdb-io/drawdb#11]
Would be nice if there is a docker image for this tool so it can be more easily run and deployed.

**Comment by timmeade** [comment]
Just wanted to add my support for this.  We may look into it.  Would be great to have locally run

**Comment by jonas-grgt** [comment]
This definitely does deserve a proper public image.

But before the image can be build I believe there should be a way to split the public promotional web-page with the app as the app itself is exposed at `/editor` while `/` exposes some kind of public app. 

Either work with some kind of configuration parameter or what I would propose is to split of the public website into a separate repository.

**Comment by 1ilit** [comment]
I've been thinking of packaging this into an electron app which would require separating the editor into some "engine" that gets injected in both the web and desktop app. If we get to do this we can have a docker image for the editor alone. I think that would make most sense

**Comment by sottey** [comment]
I threw together a dockerfile and a compose.yaml file. Minor testing copleted, but it may not be super solid. Use at your own risk.

[Drawdb-docker](https://github.com/sottey/drawdb-docker)

**Comment by BenRacicot** [comment]
Ah, nice! I arrived here because I'm running my MySQL server in a docker instance. Also Redis. It would be incredible to be able to plug in a (docker) source to see my live DB.

(I hope this is in context of this issue :))

**Comment by michabbb** [comment]
oh.... using a real mysql-connection instead of importing an SQL (structure) dump would, of course, be a burner 🔥 😏
