### ISSUE TITLE
Can increase many to many cardinality?

### ISSUE THREAD

**Issue by Jackxwb** [drawdb-io/drawdb#113]
Referring to the many to many relationship in Java JPA, it is used to express the following diagrams
![image](https://github.com/drawdb-io/drawdb/assets/34720403/8a4ee690-b770-4990-8320-4facdae09537)

Its actual working mechanism involves automatically creating an intermediate table, resulting in a structure akin to the one below
![image](https://github.com/drawdb-io/drawdb/assets/34720403/fd7def52-f779-4fa3-9fb9-694e079da703)

The current cardinality numbers may convey incorrect meanings in the illustration (as shown in Figure 1)

**Comment by 1ilit** [comment]
This is intentional. To have a many to many relationship in sql you need to have a join table
