### ISSUE TITLE
Suggestion: option to change the table width

### ISSUE THREAD

**Issue by andrecalil** [drawdb-io/drawdb#120]
Hey folks,

First of all, great project! I really like it, very well made.

It would be great if the user could tweak the table width. Either expand them all or have them auto-resize based on the text, to avoid having table and column names clipped.

I was able to change it by setting the width on `foreignObject`, but something on the UI would be super handy.

**Comment by 1ilit** [comment]
Hii! Thanks for the kind words

If you go to Settings>'Table width' you can change the size of the tables 

![image](https://github.com/drawdb-io/drawdb/assets/96800776/8403244d-a2d8-4f16-a2e0-f0a23c73c392)

**Comment by andrecalil** [comment]
Omg, here am I playing the "typical user".
You are completely right, it's already implemented, I just missed it big time. 

Thanks!

**Comment by 1ilit** [comment]
No worries
