### ISSUE TITLE
No support for SQL backticks? (`)

### ISSUE THREAD

**Issue by Tazi0** [drawdb-io/drawdb#126]
When I import a SQL with backticks, it gives me the following error:

```
SyntaxError [Ln 1, Col 32]: Expected "#", "--", "/*", [ \t\n\r], or [A-Za-z_] but "`" found.
```

**Comment by 1ilit** [comment]
Backticks are supported. Could you please give an example of what you're trying to import

**Comment by Tazi0** [comment]
> Backticks are supported. Could you please give an example of what you're trying to import

@1ilit I used a SQL export generated by PhpMyAdmin, since the error is at the beginning I will share the start:

```sql
CREATE DATABASE  IF NOT EXISTS `gouden_draak` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `gouden_draak`;
```
i guess the beginning could be removed, but I would expect drawdb would ignore these lines.

**Comment by 1ilit** [comment]
@Tazi0 thanks for bringing this up.

drawdb does ignore the lines. What's happening in this case is that the parser fails to parse the names with backticks in 'create database' statements.

I just created an issue in the parser repository. It will probably be fixed in the next release
