### ISSUE TITLE
[Bug] Problem with json import

### ISSUE THREAD

**Issue by Dev-A-Line** [drawdb-io/drawdb#133]
Problem with json import, tables are imported, but diagrams are not. 

Because of why this was needed, a bug happened and the connections moved out and stopped working, and saving without this bug was only in json.

If possible, make a timeline that will record all changes so that you can return.

![image](https://github.com/drawdb-io/drawdb/assets/14335460/ef8dae9f-141e-406d-888c-4e264b34a135)

![image](https://github.com/drawdb-io/drawdb/assets/14335460/1a5b13e2-4ebb-47f6-abd5-eaea9a73689c)

Link backup json: 
[Untitled Diagram_2024-06-07T07_42_49.051Z.json](https://github.com/user-attachments/files/15786290/Untitled.Diagram_2024-06-07T07_42_49.051Z.json)

Link bug diagram:

[Untitled Diagram_2024-06-11T10_18_47.233Z.zip](https://github.com/user-attachments/files/15786340/Untitled.Diagram_2024-06-11T10_18_47.233Z.zip)

**Comment by 1ilit** [comment]
Hey! Thanks for reporting

The ddb file seems to be corrupted.

There is a relationship with the definition: 
```json
    {
      "startTableId": 9,
      "startFieldId": 7,
      "endTableId": 10,
      "endFieldId": 0,
      "cardinality": "One to one",
      "updateConstraint": "No action",
      "deleteConstraint": "No action",
      "name": "calendars_meet_id_fk",
      "id": 20
    }
```

and this references a column in the `calendar` table with the id: 7 which does not exist.

Did you by chance delete a field from the file or how it end up referencing a column that doesn't exist?

**Comment by r-blip849** [comment]
Hi

**Comment by 1ilit** [comment]
+ added a check to prevent this. Please reopen if youre still having issues
