### ISSUE TITLE
Unable to select text in column name when editing tables

### ISSUE THREAD

**Issue by XcantloadX** [drawdb-io/drawdb#143]
Dragging in column name text box actually triggers reordering columns, making it impossible to select text.

**Comment by huyjs9** [comment]
You can hover the column and easily select the label on the popover
![CleanShot 2024-07-02 at 1 15 01@2x](https://github.com/drawdb-io/drawdb/assets/67461134/358c59c4-e6ea-4340-b3f0-a117468d4230)

**Comment by 1ilit** [comment]
plus if you focus the text field you can just double click to select
