### ISSUE TITLE
No support for store data in cloud

### ISSUE THREAD

**Issue by AnikRifat** [drawdb-io/drawdb#146]
i want a cloud solution where i can store models

**Comment by kartik1112** [comment]
and can you elaborate your feature request

**Comment by AnikRifat** [comment]
like mongo db as a cloud db solution

**Comment by kartik1112** [comment]
okay i'll try to look into it

**Comment by KawtharAlakri** [comment]
Hi @kartik1112
I would like to work on this issue, but I need to have more details if possible.

**Comment by kartik1112** [comment]
@KawtharAlakri I appreciate that you want to work on this issue but this feature will require much more computing power than what we currently have for drawDB also diagrams saved centrally is more than just saving them, we'll also need accounts, and other things as well.

**Comment by 1ilit** [comment]
I'm gonna close this issue, this is too vague and requires more than writing the code
