### ISSUE TITLE
Export as `mermaid` feature

### ISSUE THREAD

**Issue by DenuxPlays** [drawdb-io/drawdb#167]
Hey,

I thought about a new type to export the diagram.
[Mermaid](https://mermaid.js.org/) is a type of displaying diagrams and it also allows to create ER-Diagrams.
I think it would make a great addition

**Comment by LuigimonSoft** [comment]
May I help with this issue?

**Comment by happysangwan** [comment]
erDiagram
    CUSTOMER {
        int id PK
        string name
        string email
    }
    ORDER {
        int id PK
        string orderNumber
        int customerId FK
    }
    PRODUCT {
        int id PK
        string name
        decimal price
    }
    ORDER_DETAIL {
        int id PK
        int orderId FK
        int productId FK
        int quantity
    }

    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ ORDER_DETAIL : contains
    PRODUCT ||--o{ ORDER_DETAIL : included_in
