### ISSUE TITLE
Error when exporting SQL code to MySQL char and varchar field, does not export with the size

### ISSUE THREAD

**Issue by kartik1112** [drawdb-io/drawdb#170]
https://github.com/user-attachments/assets/f2c85c73-92f7-45b8-9c4a-a887bd214367

**Comment by happysangwan** [comment]
CREATE TABLE example_table (
    id INT NOT NULL,
    name VARCHAR(50),
    code CHAR(10)
);

**Comment by kartik1112** [comment]
@happysangwan can you mention the issue here?
