### ISSUE TITLE
Support for unsigned types

### ISSUE THREAD

**Issue by itning** [drawdb-io/drawdb#177]
It looks like the type selection unsigned is not supported?

**Comment by happysangwan** [comment]
CREATE TABLE example_table (
    id INT UNSIGNED NOT NULL,
    age TINYINT UNSIGNED,
    salary DECIMAL(10,2) UNSIGNED,
    score BIGINT UNSIGNED
);

**Comment by itning** [comment]
> CREATE TABLE example_table ( id INT UNSIGNED NOT NULL, age TINYINT UNSIGNED, salary DECIMAL(10,2) UNSIGNED, score BIGINT UNSIGNED );

you mean that only support import sql source？
