### ISSUE TITLE
Add Support for nvarchar Datatype

### ISSUE THREAD

**Issue by LaneZero** [drawdb-io/drawdb#18]
Currently, DrawDB does not support the nvarchar datatype. This datatype is commonly used in SQL Server databases for storing variable-length Unicode string data.
We kindly request the DrawDB development team to prioritize the implementation of nvarchar datatype support in the upcoming releases. This enhancement will significantly improve the compatibility and user experience for SQL Server database users.

![image](https://github.com/drawdb-io/drawdb/assets/46918547/659ca70a-1d32-4865-ba90-0a6e8589798a)

**Comment by jonas-grgt** [comment]
Should we make the list of available types a hodgepodge of all types across all supported databases?  

A diagram will only contain tables including types of a certain database. Therefor I would propose to add a database type connotation to a diagram that can be used to list types only specific to that database.

WDYT @1ilit ?
