### ISSUE TITLE
[Feature request] Collaboration

### ISSUE THREAD

**Issue by adamhemzal** [drawdb-io/drawdb#183]
Hi,

for some reason the feedback survey does not work, therefore I'm writing here.

It would be great to have a collaboration feature. Create a link that I can share with others so they could edit my diagrams.

**Comment by MohammedNayeemE** [comment]
most awaited feature

**Comment by 1ilit** [comment]
Thanks for pointing it out. I fixed the forms. I'll start prototyping collaboration after finishing a couple of small bugs today.
