### ISSUE TITLE
Importing sql did not bring comments here

### ISSUE THREAD

**Issue by whrss9527** [drawdb-io/drawdb#184]
<img width="243" alt="image" src="https://github.com/user-attachments/assets/b26663a7-1bc1-4845-9e65-2365b9a55df6">

Importing sql did not bring comments here

<img width="181" alt="image" src="https://github.com/user-attachments/assets/efe3d0c4-ad64-4df4-ac1c-a37fcb56853d">

**Comment by Nitiksharma2001** [comment]
can you please share a video about the issue..?

**Comment by whrss9527** [comment]
The thing is this. After I started it locally, I selected to import the sql source file in the upper left corner, and then selected a mysql sql file to import it. The format is like this:
CREATE TABLE IF NOT EXISTS `game`
(
    `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '自增 ID',
    `game_id` varchar(32) NOT NULL COMMENT '游戏 ID'
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'xxx';
Then after importing, the original 'comment' is not brought in and is displayed as 'Not Set'
