### ISSUE TITLE
Professionalize and Beautify Landing Page Sections - UI

### ISSUE THREAD

**Issue by vinitvijal** [drawdb-io/drawdb#201]
![Screenshot 2024-07-31 at 2 50 49 PM](https://github.com/user-attachments/assets/df09257f-78e5-4c37-977a-bf216d07d998)

I want to make it more appealing and professional. Can you please assign it to me.

**Comment by 1ilit** [comment]
How would you redesign it. Sure, you can give it a try

**Comment by vinitvijal** [comment]
![Screenshot 2024-08-04 at 1 04 02 PM](https://github.com/user-attachments/assets/e1a67978-e0e6-4702-a32f-307c1e2c6df8)

- A focused shadow is applied to the header and CTA buttons, while hovering buttons are shadowed to make them more appealing and increase the likelihood of clicking them.

![Screenshot 2024-08-04 at 1 04 15 PM](https://github.com/user-attachments/assets/249226f3-05eb-447e-a871-577c777f913a)

- Made a few changes to improve the appearance, focusing primarily on the cards' hover effect, Steps Padding, and Font Sizing.

![Screenshot 2024-08-04 at 1 04 30 PM](https://github.com/user-attachments/assets/2c88d6f3-76d3-40d2-926c-57bebe03e956)

![Screenshot 2024-08-04 at 1 04 35 PM](https://github.com/user-attachments/assets/1ddcdda5-1a07-48ad-b225-55d2c5a252ec)


### Can I work on it and create a pull request? If any changes are required, please let me know @1ilit .

**Comment by 1ilit** [comment]
I like it better the way it already is honestly

**Comment by vinitvijal** [comment]
ok @1ilit thank you
