### ISSUE TITLE
[Discussion] "Import diagram" popup when clicking "Import from sql"

### ISSUE THREAD

**Issue by VeejaLiu** [drawdb-io/drawdb#203]
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/ec7cffc1-00df-4ffb-bded-0ab6fc58f797">

**Comment by 1ilit** [comment]
Hey! What about it?

**Comment by VeejaLiu** [comment]
When I click 'Import from SQL', what pops up is 'Import diagram'. I don't know why this is happening.

**Comment by 1ilit** [comment]
You're supposed to upload an sql file which contains sql source code and then a diagram will be generated from the uploaded file

**Comment by VeejaLiu** [comment]
Are you serious? As a new user, I expect the behavior to allow me to paste my SQL statements under the title 'Import from SQL', and to have the option to import a file. The current design is a bit counterintuitive...

Now it seems this isn't a bug. Let me change it to a discussion.

**Comment by 1ilit** [comment]
1. It clearly explains what you're supposed to do
2. Most people have their queries in an sql file so it makes more sense to directly upload

If you wish to have an input box you're free to request it, however, I do not believe it will worth adding

**Comment by VeejaLiu** [comment]
Got you. But it still sounds strange. Considering the scenario I imagine, when my database updates, for example, by adding a new table, I usually want to add the new CREATE TABLE statement instead of replacing it with a completely new SQL file. Typically, in a production environment, we don't have that much permission. So I still stand by my point that there should be an option to insert an SQL statement, as it feels more intuitive. Thank you for your patient explanation!

**Comment by deepkokje** [comment]
maybe the title import diagram is a bit misleading.
