### ISSUE TITLE
[BUG] Cannot import SQL with checks on column level

### ISSUE THREAD

**Issue by drloloto** [drawdb-io/drawdb#208]
**Describe the bug**
When Import from SQL is used it fails on importing checks

**To Reproduce**
1. import the .ddb file
2. export as sql as it is
3. import the same file again

**Expected behavior**
should import

**Screenshots**
![image](https://github.com/user-attachments/assets/1b36cde4-8654-4693-a0f3-b003e6f996ca)
[bug.zip](https://github.com/user-attachments/files/16492359/bug.zip)

**Desktop (please complete the following information) :**
- postgres
- OS: Windows
- Browser Arc Browser (chromium)

**Comment by 1ilit** [comment]
Yep the parser seems to fails on checks. Can you please attach the sql file

**Comment by drloloto** [comment]
> Yep the parser seems to fails on checks. Can you please attach the sql file

I added the .zip :)

**Comment by 1ilit** [comment]
This isn't supposed to work. The CHECK isn't valid sql that's why the parser is failing as it should.

**Comment by drloloto** [comment]
> This isn't supposed to work. The CHECK isn't valid sql that's why the parser is failing as it should.

I think the tooltip is misleading then:
![image](https://github.com/user-attachments/assets/d88c6df8-c6c1-467a-8534-fc4ba1dc8d53)

But thanks for the clearification.
Greetings!

**Comment by 1ilit** [comment]
@drloloto how would you change it

**Comment by drloloto** [comment]
> @drloloto how would you change it

I imported a SQL Script from supabase and probably some internal functions like auth.id() didn't get recognized by drawdb. 

I think it would be neat to let the user choose to use drawdb expression check or to just use plain text. Maybe a small checkbox next to the text in my screenshot and one on the import from sql modal with "ignore expression checks" could be a solution.
