### ISSUE TITLE
[FEATURE]Primary key from composite index.

### ISSUE THREAD

**Issue by lastcmaster** [drawdb-io/drawdb#213]
**Is your feature request related to a problem? Please describe.**
Testing drawdb, I cannot find a way to designate a composite index as the primary key for a table. I can only define it as unique but that does not result in correct SQL, designating the primary key.

**Describe the solution you'd like**
A checkbox in the index tool for marking the index as the primary key and allowing this to result in database appropriate code.

**Additional context**
Most of our databases do not use generated indexes. They are unique over a few fields.

**Comment by lastcmaster** [comment]
And I just realise that you did not need to create a composite index to make a multi-key primary key. Sorry for the noise.

**Comment by karloluis** [comment]
I'm having trouble finding this feature. Any hints?
