### ISSUE TITLE
[BUG] SQL Export for SQLite does not work with multiple FOREIGN KEYs.

### ISSUE THREAD

**Issue by sunrize** [drawdb-io/drawdb#226]
**Describe the bug**
The SQL export results for the SQLite database only show one foreign key, while other foreign keys are missing.

**To Reproduce**
1. Create tables with two or more foreign key relationships.
2. Export the SQL code for the SQLite database.
3. Check the resulting SQL code.
```sql
CREATE TABLE IF NOT EXISTS "table_0" (
	"table_1" INTEGER,
	"table_2" INTEGER,
	"id" INTEGER,
	PRIMARY KEY("id"),
	FOREIGN KEY ("table_1") REFERENCES "table_1"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
        -- FOREIGN KEY ("table_2") ... is not present
);

CREATE TABLE IF NOT EXISTS "table_1" (
	"id" INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id")	
);

CREATE TABLE IF NOT EXISTS "table_2" (
	"id" INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id")	
); 
```

**Expected behavior**
All foreign keys should be present in the SQL export for the SQLite database.
```sql
CREATE TABLE IF NOT EXISTS "table_0" (
	"table_1" INTEGER,
	"table_2" INTEGER,
	"id" INTEGER,
	PRIMARY KEY("id"),
	FOREIGN KEY ("table_1") REFERENCES "table_1"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
        FOREIGN KEY ("table_2") REFERENCES "table_2"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "table_1" (
	"id" INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id")	
);

CREATE TABLE IF NOT EXISTS "table_2" (
	"id" INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id")	
); 
```

**Screenshots**
Example
![Untitled Diagram_2024-08-24T05_51_38 908Z](https://github.com/user-attachments/assets/7d331363-2e62-4310-ba24-fa5b3bb4cb96)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
None

**Comment by i-m-soumya** [comment]
Hello @sunrize ,

I have reviewed the details and attempted to replicate the problem but was unable to do so.

I have attached the screenshot of the diagram and the exported SQL schema for your reference. If there are any additional details or specific conditions under which the issue occurs, please let me know so I can further investigate.

Thank you!

### Diagram: 

![image](https://github.com/user-attachments/assets/20eade25-da2b-433f-afe3-f16a73526935)

### Exported SQL: 
`
CREATE TABLE IF NOT EXISTS "table_0" (
	"id" INTEGER NOT NULL UNIQUE,
	"fid1" INTEGER,
	"fid2" INTEGER,
	PRIMARY KEY("id")	
);

CREATE TABLE IF NOT EXISTS "table_1" (
	"id" INTEGER UNIQUE,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id") REFERENCES "table_0"("fid1")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "table_2" (
	"id" INTEGER UNIQUE,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id") REFERENCES "table_0"("fid2")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
`

**Comment by i-m-soumya** [comment]
Hello @sunrize ,

I was able to replicate the issue under specific conditions. Here’s what I observed:

### Issue Replication:
**Scenario**: When drawing relationships from table_0 to table_1 and table_2, the foreign keys are missing in the SQL export.
**Workaround**: Drawing relationships from table_1 to table_0 and table_2 to table_0 does not result in missing foreign keys.

**Comment by 1ilit** [comment]
@i-m-soumya sorry just saw your comment.  I already fixed it.

> Workaround: Drawing relationships from table_1 to table_0 and table_2 to table_0 does not result in missing foreign keys.

This wouldn't work because then the foreign keys would be in table_1 and table_2 instead of table_0

**Comment by i-m-soumya** [comment]
Cool 😎

**Comment by sunrize** [comment]
Hello @1ilit, I noticed the same issue with the 'Generic' database export to SQLite. Thank you.

**Comment by 1ilit** [comment]
@sunrize fixed, thanks for letting me know
