### ISSUE TITLE
[BUG] PostgreSQL, Import from SQL TIMESTAMPTZ parsing fail

### ISSUE THREAD

**Issue by Erim32** [drawdb-io/drawdb#232]
Issue using "import form SQL" feature with PostgreSQL : TIMESTAMPTZ 

How to reproduce

![image](https://github.com/user-attachments/assets/04252e9c-2b58-40c6-b729-30c75d51c868)

```
CREATE TABLE DEMO (
    test TIMESTAMPTZ NOT NULL
);

```
Fail

But if the datatype is  VARCHAR:

```
CREATE TABLE DEMO (
    test VARCHAR NOT NULL
);
```` 

![image](https://github.com/user-attachments/assets/80632845-5ccc-4658-b9b6-c993b0e2be90)

OK

**Comment by 1ilit** [comment]
Yes, it was fixed in this PR https://github.com/taozhi8833998/node-sql-parser/pull/2063. It will be supported once v5.4.0 comes out
