### ISSUE TITLE
[BUG] PostgreSQL Date/Time special values are marked as error

### ISSUE THREAD

**Issue by maks00x** [drawdb-io/drawdb#238]
Due to [the official Postgres documentation](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-VALUES) there are several special values for Date/Time value types. But using them in Editor is marked as problem.

**STR:**
1. Create a DB in editor
2. Specify to use PostgreSQL for it
3. Create a table
4. Add a column
5. Specify its type TIMESTAMP (probably others Date/Time types too).
6. Press the `...` button
7. Set the default value `infinity`/`now` or another special value

**Expected behavior**
Default value is set successfully

**Actual behavior**
A problem message appears in the problems list

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/9db3b9ef-498c-495b-b135-89d4a1c49c04)

**Desktop:**
 - OS: Linux Mint 20.3 Cinnamon Edition
 - Browser: Firefox 129.0

**Comment by 1ilit** [comment]
Feel free to reopen the issue if the problem still persists
