### ISSUE TITLE
[question] whether PC1 shutdown(which editing the drawdb project), the PC2 cannot access the shared link? if PC2 can, how it be implemented?

### ISSUE THREAD

**Issue by moonshineBoy** [drawdb-io/drawdb#245]
How do drawdb implements the function of share link?

I have several questions about the share link function:
1. whether the data stored in the drawdb server when sharing link?
2. if no, whether PC1 shutdown(which editing the drawdb project), the PC2 cannot access the shared link? if PC2 can, how it be implemented?

**Comment by 1ilit** [comment]
PC2 can access the link.

When you click the share button a GitHub gist gets created (it's a secret gist that no one can see). The link gets saved along with the diagram and the next time you click share the gist gets updated.

When a link with a specified share id gets loaded, the diagram gets read and displayed from the gist.
