### ISSUE TITLE
[BUG] MYSQL: incorrect syntax for SET and ENUM export SQL

### ISSUE THREAD

**Issue by csc530** [drawdb-io/drawdb#251]
When creating a MYSQL database creating a table with an `ENUM` or `SET` column type the exported SQL file (under file > export SQL) is incorrect.
Whether valid, invalid, or empty values are entered in the drawdb column's values input.
Currently, the exported syntax is

```mysql
CREATE TABLE .... (
  `enum_column` ENUM ...,
  `set_column` SET ...,
  ...
);
```

*missing brackets containing the enum/set's values*
- [enum column syntax](https://dev.mysql.com/doc/refman/8.4/en/enum.html#enum-using:~:text=size%20ENUM(%27x%2Dsmall%27%2C%20%27small%27%2C%20%27medium%27%2C%20%27large%27%2C%20%27x%2Dlarge%27))
- [set column syntax](https://dev.mysql.com/doc/refman/8.0/en/set.html#:~:text=mysql%3E%20CREATE%20TABLE%20myset%20(col%20SET(%27a%27%2C%20%27b%27%2C%20%27c%27%2C%20%27d%27))%3B)

the expected output is...

```mysql
CREATE TABLE .... (
  `enum_column` ENUM('value','val',...) ...,
  `set_column` SET('a','1',...) ...,
  ...
);
```

## To Reproduce
Steps to reproduce the behaviour:
1. Go to drawdb editor
2. Choose a MySQL database
3. Create a new table
4. Add a column of set or enum type
5. Add values for the column
6. Click on file > 'Export SQL'
7. See erroneous create table statement

## **Desktop:**
 - OS: Microsoft Windows 11 Home
 - Browser Microsoft Edge

### Additional context

Not sure if the MySQL export is for a different version of MySQL (I'm using MySQL V8.0.30), ~~I have a pr to solve the issue that I will link to this issue.~~

~~[I'm happy to open a PR with a fix to this issue](https://github.com/drawdb-io/drawdb/commit/624bd1ed2c7977b665fd85cd56869512cf22ce71)~~

**Comment by lakshyeahh** [comment]
I have understood the problem as well as high level structure of code. It can be assigned to me.
Thank You.
