### ISSUE TITLE
@csc530 is attempting to deploy a commit to the **dottle's projects** Team on [Vercel](https://vercel.com).

### ISSUE THREAD

**Issue by Amirbakhtiaro** [drawdb-io/drawdb#269]
@csc530 is attempting to deploy a commit to the **dottle's projects** Team on [Vercel](https://vercel.com).

A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=dottle's%20projects&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22804a2a5387704a0b586db7b9ffb5ef873bc28043%22%7D%2C%22id%22%3A%22QmPE37Xfad9VFqX2HZQPMcEzJJ7wfvEYwN9SP4NwTWfW6q%22%2C%22org%22%3A%22drawdb-io%22%2C%22prId%22%3A261%2C%22repo%22%3A%22drawdb%22%7D).

_Originally posted by @vercel[bot] in https://github.com/drawdb-io/drawdb/issues/261#issuecomment-2408294566_

**Comment by 1ilit** [comment]
bot?
