### ISSUE TITLE
https://github.com/drawdb-io/drawdb/pull/261#issuecomment-2408294566@csc530 is attempting to deploy a commit to the **dottle's projects** Team on [Vercel](https://vercel.com).

### ISSUE THREAD

**Issue by Amirbakhtiaro** [drawdb-io/drawdb#270]
![file-black](https://user-images.githubusercontent.com/183503387/378603141-8d9a6638-c222-44e6-a858-841e40d129fa.svg)
![file-white](https://user-images.githubusercontent.com/183503387/378603147-e13da537-2cd3-40cc-8c0b-ef0c4e267e80.svg)
![folder-closed-white](https://user-images.githubusercontent.com/183503387/378603151-c6b288a0-68f2-43c2-93cc-246f99a85181.svg)
![folder-closed-black](https://user-images.githubusercontent.com/183503387/378603153-a0160b1a-0c08-4969-8a9b-5662ca3ed4ff.svg)
![folder-open-black](https://user-images.githubusercontent.com/183503387/378603156-01c875cd-23a4-4aef-86e2-42af777a6560.svg)
![folder-open-white](https://user-images.githubusercontent.com/183503387/378603163-1446863b-6128-43a6-8e57-b0519d1cc06c.svg)
              @csc530 is attempting to deploy a commit to the **dottle's projects** Team on [Vercel](https://vercel.com).

A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=dottle's%20projects&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22804a2a5387704a0b586db7b9ffb5ef873bc28043%22%7D%2C%22id%22%3A%22QmPE37Xfad9VFqX2HZQPMcEzJJ7wfvEYwN9SP4NwTWfW6q%22%2C%22org%22%3A%22drawdb-io%22%2C%22prId%22%3A261%2C%22repo%22%3A%22drawdb%22%7D).

_Originally posted by @vercel[bot] in https://github.com/drawdb-io/drawdb/issues/261#issuecomment-2408294566_

**Comment by 1ilit** [comment]
bot
