### ISSUE TITLE
Auto layout

### ISSUE THREAD

**Issue by BenRacicot** [drawdb-io/drawdb#28]
Hi, ok draw-db is incredible, I'm obsessed!

Is there an auto-layout for use after importing? It seems all tables import on-top of each other and have to be hand sorted.

Does some form of auto arrangement exist and or is it possible to add?

**Comment by 1ilit** [comment]
Hi! It doesn't exist yet but will be added

**Comment by bgriffen** [comment]
Any word on this one? :)
