### ISSUE TITLE
[BUG] Error exporting sql statement 

### ISSUE THREAD

**Issue by carpONE** [drawdb-io/drawdb#287]
**Describe the bug**
Error exporting sql statement 

**To Reproduce**
1. Create two different types of fields 
2. An sql statement error occurs when moving the two different types of fields before and after 

**Screenshots**
![屏幕截图 2024-10-31 181007](https://github.com/user-attachments/assets/82604b80-c057-438f-ba9c-0197a3083b3c)

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by Krash0** [comment]
the same happens to me

**Comment by 1ilit** [comment]
@carpONE @Krash0 please reopen the issue if it still persists
