### ISSUE TITLE
[BUG] The app crashes on "Relationship" tab

### ISSUE THREAD

**Issue by Antiokh** [drawdb-io/drawdb#294]
**Describe the bug**
Try this schema:
https://drawdb.vercel.app/editor?shareId=d572d253d10411228450dfa7094e7eb3

Click on "Relationship", app will show a blank page.

**To Reproduce**
1. Go to https://drawdb.vercel.app/editor?shareId=d572d253d10411228450dfa7094e7eb3
2. Click on Relationship tab
3. See error (blank screen)

**Expected behavior**
Open an editor at Relationship tab

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browsers: Edge, Firefox.

**Comment by 1ilit** [comment]
please reopen if issue persists
