### ISSUE TITLE
[FEATURE]: Collaboration between users (like Figma)

### ISSUE THREAD

**Issue by Alan-Graton** [drawdb-io/drawdb#318]
Not a problem, but it kinda sucks not to have it. I think it's really important to have a feature where you can collaborate with your team, like we do on Figma.

This last week I shared one of mine diagrams link with a co-worker and she couldn't see the changes in real time, and if she changed something I wasn't able to see her changes neither.

If we could see our partner mouse and be able to change the diagrams together would be perfect.

**Comment by ademarsj** [comment]
There's already an Issue #58 about this topic.

**Comment by Alan-Graton** [comment]
> There's already an Issue #58 about this topic.

oops, sorry, I didn't see it was a duplicate feat request. I'm going to close this issue ^-^
