### ISSUE TITLE
Field Circle Icons

### ISSUE THREAD

**Issue by benranderson** [drawdb-io/drawdb#32]
Blue circle icons next to fields show out of position on Safari:

<img width="547" alt="image" src="https://github.com/drawdb-io/drawdb/assets/8963848/17f71f47-fd40-4541-885c-10f8910ba17d">

Looks fine on Google Chrome:

<img width="582" alt="image" src="https://github.com/drawdb-io/drawdb/assets/8963848/2559998d-8bf1-4362-9f3c-470450412733">

**Comment by 1ilit** [comment]
Is it like this in the editor as well?

I won't be able to try this on Mac until next week. Until then if anyone can check this out I'll really appreciate it.

**Comment by HaecheonLee** [comment]
In progress

**Comment by 1ilit** [comment]
The screenshot OP posted doesn't use `Canvas.jsx` or `Workspace.jsx` so it should be something else

**Comment by HaecheonLee** [comment]
It calls setTransform and it sets digram pan and zoom from there. The value is used in `Canvas.jsx` and it wraps `Table.jsx`. You can simply go through the DevTool and check the value.

**Comment by 1ilit** [comment]
The screenshot is from the landing page. The landing page uses SimpleCanvas which is a simplified canvas that doesn't use any of the hooks

**Comment by HaecheonLee** [comment]
Oh, I understood. I was working on Try it for yourself. It seems to be that the scale of transform doesn't work the same way in safari. It looks good when the value of scale is set to 1. By default, it's set to 0.85.

**Comment by 1ilit** [comment]
The default is 1. It's probably 0.85 because your latest diagram is being loaded which was saved with scale = 0.85

**Comment by HaecheonLee** [comment]
For the zoom value, I meant in `LandingPage.jsx`. It has the fixed value of 0.85. And, the issue in the page, Try it for yourself, seems to be the value used for translate in `Canvas.jsx`

**Comment by 1ilit** [comment]
I'll check it out, thanks
