### ISSUE TITLE
Change the order of the fields in a table

### ISSUE THREAD

**Issue by joker507** [drawdb-io/drawdb#41]
The style of this tool is exceptionally elegant, enhancing the experience of database design. Gratitude to all contributors!

But i want it include a feature that can change the order of the fields in a table.

![image](https://github.com/drawdb-io/drawdb/assets/56684300/e4223542-3656-46bc-b401-22826943e814)

**Comment by 1ilit** [comment]
Thank you @joker507. This will be supported hopefully soon
