### ISSUE TITLE
In Safari, the button in Notes and Area is not rendered on the right position.

### ISSUE THREAD

**Issue by HaecheonLee** [drawdb-io/drawdb#45]
Related to the issue #32, the button in Notes and Area is not rendered on the right position in Safari. 

- Subject Area
![Subject Area](https://github.com/drawdb-io/drawdb/assets/16802605/40c5c881-882b-4aef-9066-900b8b0017be)

- Notes
![Notes](https://github.com/drawdb-io/drawdb/assets/16802605/ca7fe7f6-6239-48cd-ab05-838c76275f2a)

**Comment by 1ilit** [comment]
Thanks for the PRs!
