### ISSUE TITLE
Enum values are not getting entered on mobile

### ISSUE THREAD

**Issue by 1ilit** [drawdb-io/drawdb#73]
#### To reproduce:
Enter value and click enter or enter comma separated values in batch and click enter

#### Expected behavior:
The values should look like tags and the input field should no longer give an error

#### Actual behavior:
Focus goes to comment input field and the enum values input still shows an error

#### Browser:
Chrome

#### OS:
Android

https://github.com/drawdb-io/drawdb/assets/96800776/7993c76f-271d-408e-bdde-958a74c5829c

**Comment by l123wx** [comment]
![image](https://github.com/drawdb-io/drawdb/assets/48666585/6816d234-bc1a-4069-91be-53ad6a172f25)

We can add the 'addOnBlur' attribute to TagInput to trigger the split behavior when the input box loses focus. I'll submit a pull request to fix this issue.
