### ISSUE TITLE
Auto swap for foreign key name

### ISSUE THREAD

**Issue by nchj** [drawdb-io/drawdb#79]
IF I create a table A with column `id`, Table B with column `id` and `a_id`, 
then A.id and B.a_id is a one to many relation

when i drag b.a_id to a.id the relation name is called B_a_id_fk, and A is primary and B is foreign, this is correct

<img width="1075" alt="图片" src="https://github.com/drawdb-io/drawdb/assets/28175310/2129eb51-fad7-4a08-85cc-d21f25fbb433">

but, when i drag a.id to b.a_id, the relation name is called A_id_fk, B is primary, A is foreign, this is not correct, 
<img width="1162" alt="图片" src="https://github.com/drawdb-io/drawdb/assets/28175310/a46133db-a2d9-4376-b4cf-b66b8f16552b">

so, i can use swap function to adjust which is the primary, then  A is primary and B is foreign, this is correct, but the foreign key name is also called A_id_fk

<img width="1181" alt="图片" src="https://github.com/drawdb-io/drawdb/assets/28175310/03e4bc78-b27b-4f61-8d50-da17a895a30a">

so can it autoamtically correct the fk name when swap?

**Comment by l123wx** [comment]
I have implemented this feature in pr #94 : )
