### ISSUE TITLE
Boolean default values not displayed

### ISSUE THREAD

**Issue by jamaa** [drawdb-io/drawdb#9]
Default values of boolean fields seem to not be displayed properly:
![grafik](https://github.com/drawdb-io/drawdb/assets/90166/6aed3e7a-72a2-48d5-9642-204ee77bd5b2)

**Comment by 1ilit** [comment]
Hello! I can't reproduce the bug.

![Screenshot 2024-04-10 025622](https://github.com/drawdb-io/drawdb/assets/96800776/b756361b-9b01-4520-854e-0b80f79a338a)

 I tried on Edge, Chrome, and Firefox and it works on all 3.

**Comment by jonas-grgt** [comment]
Same for me I cannot reproduce this.

**Comment by jamaa** [comment]
I guess it only happens when you import from source, try the following:
```sql
CREATE TABLE `Test` (
	`DefaultFalse`	BOOLEAN DEFAULT (FALSE),
	`DefaultTrue`	BOOLEAN DEFAULT (TRUE)
);
```
If I manually edit the default values in the browser afterwards, they do show up properly.

**Comment by Just-A-Pixel** [comment]
> I guess it only happens when you import from source, try the following:
> 
> ```sql
> CREATE TABLE `Test` (
> 	`DefaultFalse`	BOOLEAN DEFAULT (FALSE),
> 	`DefaultTrue`	BOOLEAN DEFAULT (TRUE)
> );
> ```
> 
> If I manually edit the default values in the browser afterwards, they do show up properly.

Did this, I can replicate the issue
