### ISSUE TITLE
Can we consider increasing the workspace

### ISSUE THREAD

**Issue by ferrymo** [drawdb-io/drawdb#90]
At present, I have found that the save function cannot be used well, and it is not possible to create isolation for multiple projects, so each time only import and export can be done.

Now the data is stored in the browser database. If the browser is accidentally cleaned and not exported in a timely manner, all data will be lost

**Comment by 1ilit** [comment]
> and it is not possible to create isolation for multiple projects, so each time only import and export can be done.

You can create multiple separate projects and then open them from File>Open if that's what you mean

> Now the data is stored in the browser database. If the browser is accidentally cleaned and not exported in a timely manner, all data will be lost

True, I'm hoping to have proper file storage in the future when we have the funds for it. Until then I've been thinking about having the user save their work to github or google drive

**Comment by ferrymo** [comment]
> You can create multiple separate projects and then open them from File>Open if that's what you mean
@1ilit  May I ask if opening and making modifications from a file will save it to a file or a browser?

**Comment by 1ilit** [comment]
The browser

**Comment by l123wx** [comment]
@ferrymo Modified projects are saved to the browser's indexedDB database, and each different project has stored in File >    Open again in Open, as long as you do not empty the browser cache, the data should not be lost

![image](https://github.com/drawdb-io/drawdb/assets/48666585/f46c6234-e027-472b-80d6-23eef8be3979)

**Comment by ferrymo** [comment]
thanks
