### ISSUE TITLE
Can we search for fields?

### ISSUE THREAD

**Issue by ferrymo** [drawdb-io/drawdb#95]
At present, we only found that we can search for tables

![image](https://github.com/drawdb-io/drawdb/assets/52627295/03eed3ea-732d-454c-8668-146fff1552e0)

**Comment by l123wx** [comment]
I think we can develop a keyword search feature. Here is the design sketch:

![image](https://github.com/drawdb-io/drawdb/assets/48666585/12b3485f-4043-419a-8514-9a4fdf14a2f6)
