### ISSUE TITLE
Can the table cards in the design area support custom field selection, such as allowing users to choose whether to add comments field？

### ISSUE THREAD

**Issue by ferrymo** [drawdb-io/drawdb#96]
![image](https://github.com/drawdb-io/drawdb/assets/52627295/b9d26b59-e564-4d24-a1e6-083fc16dd6d8)

**Comment by l123wx** [comment]
you can add comment for field in here

![image](https://github.com/drawdb-io/drawdb/assets/48666585/8ca8c800-9a5e-47dd-ba19-1012e6b9a378)

**Comment by ferrymo** [comment]
thanks
